spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-plus?serverTimezone=GMT-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lgx011023
    #配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
