spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mybatis-plus?serverTimezone=GMT-8
    url: jdbc:p6spy:mysql://localhost:3306/mybatis-plus?serverTimezone=GMT-8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: lgx011023
    #配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

